# Config File for CollegeMapper

# Google API KEY
# You can get one here: 
# https://developers.google.com/maps/documentation/geocoding/start
API_KEY = ''

# Output file.  Path to Where you want to output the 
# csv file results
OUTPUT_FILE = ''

# String of colleges to scrape.  Every college should
# Be put on a separate line (Separated by newline \n)
ADDRESSES = [
    'Arizona State University',
    'Auburn University',
    'Ball State University',
    'Brandeis University',
    'Brigham Young University',
    'Brown University',
    'Boston University',
    'Carnegie Mellon University',
    'Colorado State University',
    'Columbia University',
    'Cornell University',
    'Dalhousie University',
    'DePaul University',
    'Drexel University',
    'Duke University',
    'Georgia Institute of Technology',
    'Georgia State University',
    'Harvard University',
    'Indiana University',
    'Iowa State University',
    'Johns Hopkins University',
    'Kansas State University',
    'Massachusetts Institute of Technology',
    'Michigan State University',
    'Mississippi State University',
    'Mississippi State University Artificial Intelligence Home Page',
    'New Jersey Institute of Technology',
    'New Mexico State University',
    'New York University',
    'North Carolina State University',
    'Northwestern University',
    'Northwestern University, Qualitative Reasoning Group',
    'The Ohio State University',
    'Oregon Health & Science University',
    'Oregon State University',
    'Pace University',
    'Purdue University',
    'Rensselaer Polytechnic Institute',
    'Rice University',
    'Rutgers University',
    'Stanford University',
    'State University of New York, Buffalo',
    'Syracuse University',
    'Temple University',
    'Texas A&M University',
    'Texas Tech University',
    'Tufts University',
    'Tulane University',
    'University of Alabama in Huntsville',
    'University of Arkansas',
    'University of California, Berkeley',
    'University of California, Davis',
    'University of California, Irvine',
    'University of California, Los Angeles',
    'University of California, San Diego',
    'University of California, Santa Cruz',
    'University of Central Florida',
    'University of Chicago',
    'University of West Florida',
    'University of Georgia',
    'University of Illinois, Chicago',
    'University of Illinois, Urbana Champaign',
    'University of Iowa',
    'University of Kansas',
    'University of Kentucky',
    'University of Louisville',
    'University of Maine',
    'University of Maryland, College Park',
    'University of Maryland, Baltimore County',
    'University of Massachusetts, Amherst',
    'University of Michigan',
    'University of Minnesota',
    'University of New Hampshire',
    'University of New Mexico',
    'University of Oregon',
    'University of Pennsylvania',
    'University of Pittsburgh',
    'University of Rochester',
    'University of South Carolina',
    'University of Southern California',
    'University of Southern California Information Sciences Institute',
    'University of Southern California Institute for Creative Technologies',
    'University of Tennessee, Knoxville',
    'University of Texas, Austin',
    'University of Texas, Dallas',
    'University of Utah',
    'University of Vermont',
    'University of Virginia',
    'University of Washington',
    'University of Wisconsin, Madison',
    'University of Wisconsin, Milwaukee',
    'Washington University in St. Louis',
    'Wayne State University',
    'Worcester Polytechnic Institute',
    'Wright State University',
    'Yale University'
]